import localFont from "next/font/local";

const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Adjusted path to be relative to the public directory
  variable: "--font-geist-sans",
  weight: "100 900", // Ensure these weights are supported by your font files
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Adjusted path to be relative to the public directory
  variable: "--font-geist-mono",
  weight: "100 900", // Ensure these weights are supported by your font files
});

export const metadata = {
  title: "Nim calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
